config/routes.rb
TodoApp::Application.routes.draw do
  resources :users do
    resources :todos
  end

  resources :todos

  resources :logins

  delete 'logout' => 'logins#destroy'

  root 'logins#new'

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	validates :task, presence: true
	validates_presence_of :due
	default_scope :order => 'todos.due' #order by due

	belongs_to :user
end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base
  has_many :todos
  before_save :encrypt_password

  def encrypt_password
    if self.password_digest.present?
      self.password_digest = Digest::SHA1.hexdigest(self.password_digest)
    else
      self.password_digest = self.password_digest_was
    end
  end

  def registered?
  	new_user = User.find_by email:self.email
  	if new_user and new_user.password_digest == Digest::SHA1.hexdigest(self.password_digest)
  		self.id = new_user.id
  		return true
  	else
  		return false
  	end
  		
    # ここを考えて下さい。email/passwordで認証できれば true を認証できなければ falseを戻します。
    # さらに、認証できた場合はインスタンスのidに認証されたユーザーのidが入るようにします
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new logins_params
  	if @user.registered?
  		session[:login] = @user.id
  		redirect_to todos_path
  	else
  		render "new", notice: 'Invalid email/password combination'
  	end
  end

  def destroy
  	session[:login] = nil
  	redirect_to root_url
  end

  private
    def logins_params
      params.require(:user).permit(:password_digest, :email)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  # GET /todos
  def index
    if params[:user_id]
      @todos = Todo.where(user_id: params[:user_id]).page(params[:page]).per(3)
    else
      @todos = Todo.all.page(params[:page]).per(3)
    end
  end

  # GET /todos/1
  def show
    if request.xhr?
      render partial: 'show_body'
    end
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
    if request.xhr?
      render partial: 'form'
    end
  end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo, notice: 'Todo was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
      if @remote
        respond_to do |format|
            format.js
        end
      else
        redirect_to @todo, notice: 'Todo was successfully updated.'
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_params
      params.require(:todo).permit(:due, :task, :memo, :user_id)
    end

    def require_login
      redirect_to(root_url, notice: 'Please Log In.') unless session[:login]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :password_digest, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
	def new_line(s)
		# "\n" = "<br>"
		raw html_escape(s).gsub(/\n/, '<br />')#.html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>Login</h1>
<p id="notice"><%= notice %></p>
<%= form_for @user, url:logins_path do |f| %>
<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email, type: "email" %>
</div>
<div class="field">
	<%= f.label :password %>
	<%= f.text_field :password_digest, type: "password" %>
</div>
<div class="actions">
	<%= f.submit "Log In" %>
</div>
<% end %>

app/views/todos/_form.html.erb
<%= form_for(@todo, remote:@remote) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= @todo.errors.count %> つの間違いがあります :</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit-id" data-id="<%=@todo.id%>">

  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, User.all.map{|u| [u.name,u.id]} %>
  </div>
  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_show_body.html.erb
<p>
  <strong>Due:</strong>
  <%= @todo.due %>
</p>

<p>
  <strong>Name:</strong>
  <%= @todo.user.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @todo.task %>
</p>

<p>
  <strong>Memo:</strong>
  <%= new_line(@todo.memo) %>
<!-- simple_format(@todo.memo) -->
</p>

app/views/todos/_todo.html.erb
<td><%= todo.due %></td>
<td><%= todo.user.name %></td>
<td><%= todo.task %></td>
<td>
  <%= link_to 'Quick Show', todo, remote:true, class:"quick_show" %>
  <%= link_to 'Show', todo %>
</td>
<td><%= link_to 'Quick Edit', edit_todo_path(todo), remote:true, class:"quick_edit"  %></td>
<td><%= link_to 'Edit', edit_todo_path(todo) %></td>
<td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>
<td><%= link_to 'Logout', "/logout", method: :delete, data: { confirm: 'Are you sure?' } %></td>
<table>
  <thead>
    <tr>
      <th>Due</th>
      <th>Name</th>
      <th>Task</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr id="todo-<%=todo.id%>">
        <td><%= todo.due %></td>
        <td><%= todo.user.name %></td>
        <td><%= todo.task %></td>
        <td>
          <%= link_to 'Quick Show', todo, remote:true, class:"quick_show" %>
          <%= link_to 'Show', todo %>
        </td>
        <td><%= link_to 'Quick Edit', edit_todo_path(todo), remote:true, class:"quick_edit"  %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @todos %>
<div id="show_area">
</div>
<%=javascript_tag do%>
  $("a.quick_show").on('ajax:success',function(evt,data,status,xhr){
    $("#show_area").html(data);
  })
  $("a.quick_edit").on('ajax:success',function(evt,data,status,xhr){
    $("#show_area").html(data);
  })
<% end %>
<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'show_body'%>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/update.js.erb
var id = $(".edit-id").data("id")
$("#todo-"+id).html("<%=j render partial: "todo", object: @todo %>") 
$("#todo-"+id+" a.quick_edit").on('ajax:success',function(evt,data,status,xhr){
  $("#show_area").html(data);
})
$("#todo-"+id+" a.quick_show").on('ajax:success',function(evt,data,status,xhr){
    $("#show_area").html(data);
})
$("#show_area").html("<%=j render 'show_body'%>");

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%= link_to 'Back', users_path %>
<%= link_to 'Todos', user_todos_path(@user)%>